from .categoria_produto import CategoriaProdutoViewSet
from .produto import ProdutoViewSet
from .servico import ServicoViewSet
from .tipo_servico import TipoServicoViewSet
from .avaliacao import AvaliacaoViewSet
from .favorito import FavoritoViewSet
from .compra import CompraViewSet 
from .itens_compra import ItensCompraViewSet
from .produto_foto import ProdutoFotoViewSet
from .solicita import SolicitaViewSet