# Generated by Django 5.1.5 on 2025-03-16 20:46

import django.db.models.deletion
import venda.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_remove_ong_email_remove_petshop_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='TipoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=70)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Serviço',
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formapagamento', models.IntegerField(choices=[(1, 'Cartão'), (2, 'Pix'), (3, 'Boleto')])),
                ('status', models.IntegerField(choices=[(1, 'Carrinho'), (2, 'Realizado'), (3, 'Pago'), (4, 'Entregue'), (5, 'Cancelado'), (6, 'Retorno')], default=1)),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='accounts.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=65)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo', models.PositiveIntegerField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='venda.categoriaproduto')),
                ('petshop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='accounts.petshop')),
            ],
        ),
        migrations.CreateModel(
            name='ItensCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='venda.compra')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='venda.produto')),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to=venda.models.produto_foto_path)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='venda.produto')),
            ],
            options={
                'verbose_name': 'Foto do Produto',
                'verbose_name_plural': 'Fotos dos Produtos',
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('petshop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicos', to='accounts.petshop')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicos', to='venda.tiposervico')),
            ],
            options={
                'verbose_name_plural': 'Serviços',
            },
        ),
        migrations.CreateModel(
            name='Solicita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Requerido'), (2, 'Cancelado'), (3, 'Concluído'), (4, 'Rejeitado')], default=1)),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='accounts.cliente')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='venda.servico')),
            ],
            options={
                'verbose_name': 'Solicitação',
                'verbose_name_plural': 'Solicitações',
            },
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='accounts.cliente')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='venda.produto')),
                ('servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='venda.servico')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('cliente', 'produto'), name='unique_favorito_produto'), models.UniqueConstraint(fields=('cliente', 'servico'), name='unique_favorito_servico')],
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(blank=True, null=True)),
                ('valor', models.PositiveSmallIntegerField()),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='accounts.cliente')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='venda.produto')),
                ('servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='venda.servico')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('cliente', 'produto'), name='unique_avaliacao_produto'), models.UniqueConstraint(fields=('cliente', 'servico'), name='unique_avaliacao_servico')],
            },
        ),
    ]
