# Generated by Django 5.0.3 on 2025-02-05 23:02

import django.db.models.deletion
import venda.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProduto',
            fields=[
                ('ctpid', models.AutoField(primary_key=True, serialize=False)),
                ('ctpnome', models.CharField(max_length=100)),
                ('ctpdescricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'categoria_produto',
            },
        ),
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('fpgid', models.AutoField(primary_key=True, serialize=False)),
                ('fpgdescricao', models.CharField(max_length=65)),
            ],
            options={
                'db_table': 'forma_pagamento',
            },
        ),
        migrations.CreateModel(
            name='TipoServico',
            fields=[
                ('tpsid', models.AutoField(primary_key=True, serialize=False)),
                ('tpsnome', models.CharField(max_length=70)),
                ('tpsdescricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipo_servico',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('proid', models.AutoField(primary_key=True, serialize=False)),
                ('pronome', models.CharField(max_length=65)),
                ('propreco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prosaldo', models.PositiveIntegerField(blank=True, null=True)),
                ('procategoria', models.ForeignKey(db_column='procategoria_produto_ctpid', on_delete=django.db.models.deletion.CASCADE, to='venda.categoriaproduto')),
                ('propetshop', models.ForeignKey(db_column='propetshop_ptsid', on_delete=django.db.models.deletion.CASCADE, to='accounts.petshop')),
            ],
            options={
                'db_table': 'produto',
            },
        ),
        migrations.CreateModel(
            name='ProdutoFoto',
            fields=[
                ('prfid', models.AutoField(primary_key=True, serialize=False)),
                ('prffoto', models.ImageField(upload_to=venda.models.produto_foto_path, verbose_name='Foto do Produto')),
                ('produto_proid', models.ForeignKey(db_column='produto_proid', on_delete=django.db.models.deletion.CASCADE, to='venda.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Foto do Produto',
                'verbose_name_plural': 'Fotos dos Produtos',
                'db_table': 'produto_foto',
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('serid', models.AutoField(primary_key=True, serialize=False)),
                ('serdescricao', models.CharField(blank=True, max_length=200, null=True)),
                ('servalor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('serpetshop', models.ForeignKey(db_column='serpetshop_ptsid', on_delete=django.db.models.deletion.CASCADE, to='accounts.petshop')),
                ('sertipo', models.ForeignKey(db_column='sertipo_servico_tpsid', on_delete=django.db.models.deletion.CASCADE, to='venda.tiposervico')),
            ],
            options={
                'db_table': 'servico',
            },
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('favid', models.AutoField(primary_key=True, serialize=False)),
                ('favdatahora', models.DateTimeField(auto_now_add=True)),
                ('favpessoa', models.ForeignKey(db_column='favpessoa_pesid', on_delete=django.db.models.deletion.CASCADE, to='accounts.pessoa')),
                ('favproduto', models.ForeignKey(blank=True, db_column='favproduto_proid', null=True, on_delete=django.db.models.deletion.CASCADE, to='venda.produto')),
                ('favservico', models.ForeignKey(blank=True, db_column='favservico_serid', null=True, on_delete=django.db.models.deletion.CASCADE, to='venda.servico')),
            ],
            options={
                'db_table': 'favorito',
            },
        ),
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('carid', models.AutoField(primary_key=True, serialize=False)),
                ('carquantidade', models.PositiveIntegerField()),
                ('carprecototal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('carpessoa', models.ForeignKey(db_column='carpessoa_pesid', on_delete=django.db.models.deletion.CASCADE, to='accounts.pessoa')),
                ('carproduto', models.ForeignKey(blank=True, db_column='carproduto_proid', null=True, on_delete=django.db.models.deletion.CASCADE, to='venda.produto')),
                ('carservico', models.ForeignKey(blank=True, db_column='carservico_serid', null=True, on_delete=django.db.models.deletion.CASCADE, to='venda.servico')),
            ],
            options={
                'db_table': 'carrinho',
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('avaid', models.AutoField(primary_key=True, serialize=False)),
                ('avadescricao', models.TextField(blank=True, null=True)),
                ('avavalor', models.PositiveSmallIntegerField()),
                ('avadatahora', models.DateTimeField(auto_now_add=True)),
                ('avapessoa', models.ForeignKey(db_column='avapessoa_pesid', on_delete=django.db.models.deletion.CASCADE, to='accounts.pessoa')),
                ('avaproduto', models.ForeignKey(blank=True, db_column='avaproduto_proid', null=True, on_delete=django.db.models.deletion.CASCADE, to='venda.produto')),
                ('avaservico', models.ForeignKey(blank=True, db_column='avaservico_serid', null=True, on_delete=django.db.models.deletion.CASCADE, to='venda.servico')),
            ],
            options={
                'db_table': 'avaliacao',
            },
        ),
        migrations.CreateModel(
            name='Solicita',
            fields=[
                ('solid', models.AutoField(primary_key=True, serialize=False)),
                ('soldthr', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('solstatus', models.CharField(choices=[('RE', 'Requerido'), ('CA', 'Cancelado'), ('CO', 'Concluído')], max_length=2)),
                ('pessoa_pesid', models.ForeignKey(db_column='pessoa_pesid', on_delete=django.db.models.deletion.CASCADE, to='accounts.pessoa')),
                ('servico_serid', models.ForeignKey(db_column='servico_serid', on_delete=django.db.models.deletion.CASCADE, to='venda.servico')),
            ],
            options={
                'verbose_name': 'Solicitação',
                'verbose_name_plural': 'Solicitações',
                'db_table': 'solicita',
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('venid', models.AutoField(primary_key=True, serialize=False)),
                ('venvalortotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vendatahora', models.DateTimeField(auto_now_add=True)),
                ('venquantidade', models.PositiveIntegerField()),
                ('venformapagamento', models.ForeignKey(db_column='venformapagamento_fpgid', on_delete=django.db.models.deletion.DO_NOTHING, to='venda.formapagamento')),
                ('venpessoa', models.ForeignKey(db_column='venpessoa_pesid', on_delete=django.db.models.deletion.CASCADE, to='accounts.pessoa')),
                ('venproduto', models.ForeignKey(db_column='venproduto_proid', on_delete=django.db.models.deletion.CASCADE, to='venda.produto')),
            ],
            options={
                'db_table': 'venda',
            },
        ),
        migrations.AddConstraint(
            model_name='favorito',
            constraint=models.UniqueConstraint(fields=('favpessoa', 'favproduto'), name='unique_favorito_produto'),
        ),
        migrations.AddConstraint(
            model_name='favorito',
            constraint=models.UniqueConstraint(fields=('favpessoa', 'favservico'), name='unique_favorito_servico'),
        ),
    ]
