# Generated by Django 5.0.3 on 2025-02-05 23:02

import adocao.models
import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetPorte',
            fields=[
                ('ptpid', models.AutoField(primary_key=True, serialize=False)),
                ('ptpnome', models.CharField(max_length=100)),
                ('ptpdescricao', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'pet_porte',
            },
        ),
        migrations.CreateModel(
            name='PetRaca',
            fields=[
                ('ptrid', models.AutoField(primary_key=True, serialize=False)),
                ('ptrnome', models.CharField(max_length=65)),
            ],
            options={
                'db_table': 'pet_raca',
            },
        ),
        migrations.CreateModel(
            name='PetTipo',
            fields=[
                ('pttid', models.AutoField(primary_key=True, serialize=False)),
                ('pttnome', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'pet_tipo',
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('petid', models.AutoField(primary_key=True, serialize=False)),
                ('petnome', models.CharField(max_length=100, verbose_name='Nome do Pet')),
                ('petsexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('N', 'Não Informado')], max_length=1, verbose_name='Sexo do Pet')),
                ('petcastrado', models.CharField(choices=[('CAS', 'Castrado'), ('NCA', 'Não Castrado'), ('DES', 'Desconhecido')], max_length=3, verbose_name='Status de Castração')),
                ('petdtnascto', models.DateField(help_text='A data de nascimento não pode ser futura.', validators=[django.core.validators.MaxValueValidator(datetime.date(2025, 2, 5))], verbose_name='Data de Nascimento')),
                ('petpeso', models.FloatField(verbose_name='Peso do Pet')),
                ('pessoa_pesid', models.ForeignKey(blank=True, db_column='pessoa_pesid', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.pessoa', verbose_name='Dono do Pet')),
                ('pet_porte_ptpid', models.ForeignKey(db_column='pet_porte_ptpid', on_delete=django.db.models.deletion.CASCADE, to='adocao.petporte', verbose_name='Porte do Pet')),
                ('pet_raca_ptrid', models.ForeignKey(db_column='pet_raca_ptrid', on_delete=django.db.models.deletion.CASCADE, to='adocao.petraca', verbose_name='Raça do Pet')),
                ('pet_tipo_pttid', models.ForeignKey(db_column='pet_tipo_pttid', on_delete=django.db.models.deletion.CASCADE, to='adocao.pettipo', verbose_name='Tipo do Pet')),
            ],
            options={
                'verbose_name': 'Pet',
                'verbose_name_plural': 'Pets',
                'db_table': 'pet',
            },
        ),
        migrations.CreateModel(
            name='PetAdocao',
            fields=[
                ('adoid', models.AutoField(primary_key=True, serialize=False)),
                ('adostatus', models.CharField(max_length=10)),
                ('ong_ongid', models.ForeignKey(db_column='ong_ongid', on_delete=django.db.models.deletion.CASCADE, to='accounts.ong')),
                ('pet_petid', models.ForeignKey(db_column='pet_petid', on_delete=django.db.models.deletion.CASCADE, to='adocao.pet')),
            ],
            options={
                'db_table': 'pet_adocao',
            },
        ),
        migrations.CreateModel(
            name='PetFoto',
            fields=[
                ('pftid', models.AutoField(primary_key=True, serialize=False)),
                ('pftfoto', models.ImageField(upload_to=adocao.models.pet_foto_path, verbose_name='Foto do Pet')),
                ('pet_petid', models.ForeignKey(db_column='pet_petid', on_delete=django.db.models.deletion.CASCADE, to='adocao.pet', verbose_name='Pet')),
            ],
            options={
                'verbose_name': 'Foto do Pet',
                'verbose_name_plural': 'Fotos dos Pets',
                'db_table': 'pet_foto',
            },
        ),
        migrations.AddField(
            model_name='petraca',
            name='pet_tipo_pttid',
            field=models.ForeignKey(db_column='pet_tipo_pttid', on_delete=django.db.models.deletion.DO_NOTHING, to='adocao.pettipo'),
        ),
        migrations.CreateModel(
            name='TentativaAdota',
            fields=[
                ('ttaid', models.AutoField(primary_key=True, serialize=False)),
                ('ttastatus', models.CharField(choices=[('RE', 'Requisitado'), ('AC', 'Aceito'), ('NE', 'Negado'), ('AD', 'Adotado'), ('NA', 'Não Adotado')], max_length=2, verbose_name='Status da Tentativa')),
                ('ttadthora', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora da Tentativa')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data e Hora da Atualização')),
                ('tta_petadocao', models.ForeignKey(db_column='tta_petadocao', on_delete=django.db.models.deletion.CASCADE, to='adocao.petadocao', verbose_name='Pet para Adoção')),
                ('ttapes', models.ForeignKey(db_column='ttapes', on_delete=django.db.models.deletion.CASCADE, to='accounts.pessoa', verbose_name='Pessoa')),
            ],
            options={
                'verbose_name': 'Tentativa de Adoção',
                'verbose_name_plural': 'Tentativas de Adoção',
                'db_table': 'tentativa_adota',
            },
        ),
    ]
