# Generated by Django 5.0.3 on 2025-02-05 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('endid', models.AutoField(primary_key=True, serialize=False)),
                ('endcep', models.CharField(max_length=9)),
                ('endlogradouro', models.CharField(max_length=255)),
                ('endbairro', models.CharField(max_length=100)),
                ('endcidade', models.CharField(max_length=100)),
                ('endestado', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'endereco',
            },
        ),
        migrations.CreateModel(
            name='Ong',
            fields=[
                ('ongid', models.AutoField(primary_key=True, serialize=False)),
                ('ongnome', models.CharField(max_length=65)),
                ('ongtelefone', models.CharField(max_length=15)),
                ('ongemail', models.CharField(max_length=70)),
                ('endereco', models.ForeignKey(db_column='ongendereco_endid', on_delete=django.db.models.deletion.CASCADE, to='accounts.endereco')),
            ],
            options={
                'db_table': 'ong',
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('pesid', models.AutoField(primary_key=True, serialize=False)),
                ('pescpf', models.CharField(max_length=11, unique=True)),
                ('pesdtnascto', models.DateField()),
                ('pessexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('pesemail', models.CharField(max_length=70, unique=True)),
                ('pestelefone', models.CharField(max_length=15)),
                ('pesnome', models.CharField(max_length=100)),
                ('endereco', models.ForeignKey(db_column='endereco_endid', on_delete=django.db.models.deletion.CASCADE, to='accounts.endereco')),
            ],
            options={
                'db_table': 'pessoa',
            },
        ),
        migrations.CreateModel(
            name='Petshop',
            fields=[
                ('ptsid', models.AutoField(primary_key=True, serialize=False)),
                ('ptsnome', models.CharField(max_length=100)),
                ('ptscnpj', models.CharField(max_length=20)),
                ('ptstelefone', models.CharField(max_length=15)),
                ('ptsemail', models.CharField(max_length=70, unique=True)),
                ('endereco', models.ForeignKey(db_column='ptsendereco_endid', on_delete=django.db.models.deletion.CASCADE, to='accounts.endereco')),
            ],
            options={
                'db_table': 'petshop',
            },
        ),
    ]
